### ISSUE TITLE
player names returning incorrectly

### ISSUE THREAD

**Issue by BenBrownCreative** [BenBrownCreative/game-event-manager#32]
when fetching plays data on the client the players name is returning user names as the same value for all names but the owner of the play

![image](https://user-images.githubusercontent.com/33357404/91096501-c31e2d00-e623-11ea-9c5d-7cc853178f3f.png)

**Comment by meyer-mcmains** [comment]
@BenBrownCreative I think something is wrong on the client server data looks correct (I'm assuming you are showing the last play?)

![image](https://user-images.githubusercontent.com/8660578/91101917-b999c280-e62d-11ea-842c-dc804f4fbb56.png)

**Comment by BenBrownCreative** [comment]
i copied the query from the server and when the client calls it here is what i see after logging the play.

![image](https://user-images.githubusercontent.com/33357404/91102323-8dcb0c80-e62e-11ea-8453-04d6a9ed3f39.png)
