### ISSUE TITLE
additional user stats

### ISSUE THREAD

**Issue by BenBrownCreative** [BenBrownCreative/game-event-manager#59]
Additional parsed user stats for the profile page. 

- [x] total games owned
- [x] total expansions owned
- [x] total games played this year
- [x] total unique games played this year
- [x] total games played all time
- [x] total unique games played all time

**Comment by meyer-mcmains** [comment]
@BenBrownCreative In order to get the last 4 stats I'm going to to have to hit the `/plays` endpoint.
